
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run:
          docker build -t app .
          
          docker login -u sudipdasvu -p dckr_pat_G9Ix0tMlAiReRB8EeX6zJCH3Zbo

          docker tag app:latest sudipdasvu/app:latest
          docker push sudipdasvu/app
